name: Build Mod

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - target: Android32
            abi: armeabi-v7a
          - target: Android64
            abi: arm64-v8a

    steps:
      - uses: actions/checkout@v4

      - name: Download Geode SDK Source
        run: |
          # Clean up old data entirely
          rm -rf geode-sdk geode-main sdk.zip
          
          # Pull the repository zip file
          wget https://github.com/geode-sdk/geode/archive/refs/heads/main.zip -O sdk.zip
          unzip sdk.zip
          
          # Rename using absolute local relative matching
          mv geode-main geode-sdk

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DGEODE_TARGET=${{ matrix.config.target }} \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.config.abi }}

      - name: Build Mod
        run: cmake --build build --config Release
        
