name: Build Mod

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - target: Android32
          - target: Android64

    steps:
      - uses: actions/checkout@v4

      - name: Install Geode CLI Manually
        run: |
          # Use Geode's official bash installation script instead of guessing the URL
          wget -qO- https://raw.githubusercontent.com/geode-sdk/cli/main/loader.sh | bash
          
          # Add the newly created geode directory to the GitHub path
          echo "$HOME/.geode/bin" >> $GITHUB_PATH
          
          # Force the CLI to install the header files right now
          $HOME/.geode/bin/geode sdk install-binaries

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DGEODE_TARGET=${{ matrix.config.target }} \
            -DCMAKE_PREFIX_PATH="$HOME/.geode/sdk" \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.config.target == 'Android32' && 'armeabi-v7a' || 'arm64-v8a' }}

      - name: Build Mod
        run: cmake --build build --config Release
        
