cmake_minimum_required(VERSION 3.25)
project(fpsbypasser)

# Tell CMake exactly where our custom downloaded SDK folder lives
set(GEODE_SDK_DIR "${CMAKE_CURRENT_SOURCE_DIR}/geode-sdk-source")
list(APPEND CMAKE_PREFIX_PATH "${GEODE_SDK_DIR}")
list(APPEND CMAKE_MODULE_PATH "${GEODE_SDK_DIR}/loader/cmake")
set(Geode_DIR "${GEODE_SDK_DIR}/loader/cmake")

find_package(Geode REQUIRED)

add_geode_mod(com.developer.fpsbypasser
    VERSION 1.0.0
    ANDROID
)

target_sources(com.developer.fpsbypasser PRIVATE main.cpp)
